### ISSUE TITLE
Product Submission: TSD Genie Update Package

### ISSUE THREAD

**Issue by hessionra** [ICPI/Coordination#12]
The Treatment Cluster (@MicSherlock ) submitted the TSD Genie Update Package for Leads' Review on 6/11. 

The reviewers were assigned during the Leads' meeting on 6/18: @jaliasd and @HoustonJamie and the review/feedback deadline scheduled for COB 6/22.

The materials for review can be found on [SharePoint](https://www.pepfar.net/OGAC-HQ/icpi/Products/Forms/AllItems.aspx?RootFolder=%2FOGAC%2DHQ%2Ficpi%2FProducts%2FICPI%20Approved%20Tools%20%28Most%20Current%20Versions%29%2FTreatment%20Dashboards%2FTreatment%20Summary%20Dashboard%20%28TSD%29%2FTSD%20Update%20Package%20for%20Genie%20Site%20by%20IM%20extract&FolderCTID=0x0120004DAC66286D0B8344836739DA850ACB95&View=%7B58E3102A%2DC027%2D4C66%2DA5C7%2D84FEBE208B3C%7D).

**Comment by jb3436** [comment]
**Title of Product** : TSD Genie Update Package

**Date Submitted for Leads&#39; Review** : June 11

**Submitted by** : Michelle Williams-Sherlock

**Reviewers** : Josh Davis, Jamie Houston, and Jasmine Buttolph

**Status** : Approved Pending Suggested Revisions

**Next Steps:** Resubmit when complete as an FYI and for our records. We will not do a formal re-review.

**SharePoint link** : [HERE](https://www.pepfar.net/OGAC-HQ/icpi/Products/Forms/AllItems.aspx?RootFolder=%2FOGAC%2DHQ%2Ficpi%2FProducts%2FICPI%20Approved%20Tools%20%28Most%20Current%20Versions%29%2FTreatment%20Dashboards%2FTreatment%20Summary%20Dashboard%20%28TSD%29%2FTSD%20Update%20Package&FolderCTID=0x0120004DAC66286D0B8344836739DA850ACB95&View=%7B58E3102A%2DC027%2D4C66%2DA5C7%2D84FEBE208B3C%7D )



**Feedback** :

_General Feedback and Suggestions_

- This reflects a significant amount of work and is truly impressive. This is definitely in line with the strategic direction that ICPI is moving towards and we would like to thank your team for continuing to be at the forefront of moving these types of integrated self-serve initiatives forward.
- Streamlining the process
- Reminder that while product is under review, it should not be listed as &quot;Approved&quot; in the Products Library. Needs to be in draft or within the Cluster folder in the General Library. I see that the parent folder is pending, which should mask it from the public unless they have a direct link.

_Specific Suggestions_

- Received error the first time I ran it because my R wasn&#39;t installed correctly by IT support.  So the packages couldn&#39;t download.  Aliyah had created the attached instructions for CDC folks at our annual meeting, which resolved the problem, but it would be good to include this with the instructions and to help people identify when they are getting errors from not having R optimized properly.
- Slide 33 in PPT and step 7 on page 14 have a screenshot from the standard MSD import instructions and not the specific tool so the written instructions don&#39;t match the picture, this should be updated to correct this to reduce confusion at this step
- Slide 37 in PPT and step 8 on page 17 have the wrong excel short cut, should be CLT+shift+END not CLT+A (you get an error when you paste using CLT+A)
- Suggest adding context in the word document and in all parts of the &quot;package&quot; about the purpose, audience, and end use. As a reviewer, I was only sent part of the package and struggled to identify all of the contextual pieces. Once I received the full package, more came into focus, but packages get separated and you may want to paste the guide into the excel document template as well so people have fewer things to potentially lose.
- Suggesting adding authors, contributors, and contact information to the document and excel when you paste it into the template.

FYI @MicSherlock @KatieOC @HoustonJamie @jaliasd

**Comment by jb3436** [comment]
8/16: Sent email follow up to cluster leads for a link to the final product that incorporates the above suggestions

Email Subject: RE: APPROVED: TSD Genie Update Package Review
