### ISSUE TITLE
Product Submission: New AGYW_PREV Visuals in DREAMS Dashboard

### ISSUE THREAD

**Issue by hessionra** [ICPI/Coordination#63]
Submitted by Kimi (5/20) on behalf of Prevention Cluster for new AGYW_PREV Visuals in DREAMS Dashboard. Can be found on [SharePoint](https://www.pepfar.net/OGAC-HQ/icpi/Shared%20Documents/Forms/AllItems.aspx?RootFolder=%2FOGAC%2DHQ%2Ficpi%2FShared%20Documents%2FClusters%2FPrevention%2FWorking%20Folder%2FDREAMS%2FFY19%2C%20Q2&FolderCTID=0x012000C815322C717A7E4B8164EA374FA254EC002682B939F9BED347BD49E43D77D3C691&View=%7B94C838B2%2DE166%2D4122%2DB8B4%2D7BEB9E1BC12B%7D). 

To be put on Leads' agenda for meeting 5/20.

JP and Jamie to review, submit comments by COB 5/23.

**Comment by jla7** [comment]
Here's some preliminary feedback.  Will double check accuracy of numbers shortly.

Update sequence in the bar chart x axis. 

![image](https://user-images.githubusercontent.com/18124150/58280447-9e773d80-7d6e-11e9-8d15-33ba2a975802.png)

In Figure 3, include values for "DREAMS fully completed" to be consistent with the bar graphs.
![image](https://user-images.githubusercontent.com/18124150/58280758-5f95b780-7d6f-11e9-8831-2ab34bc8f8ab.png)

**Comment by HoustonJamie** [comment]
Kimi

Additionally, I noticed in the updated version you sent, for South Africa and Mozambique the formatting for the color in the bar charts is inconsistent with the other OUs.  I think its something about how they only have 1 or 2 values reported instead of all three options.

Otherwise looks great.  Cleared with minor comments.

Jamie

https://www.pepfar.net/OGAC-HQ/icpi/Shared%20Documents/Forms/AllItems.aspx?RootFolder=%2FOGAC%2DHQ%2Ficpi%2FShared%20Documents%2FClusters%2FPrevention%2FWorking%20Folder%2FDREAMS%2FFY19%2C%20Q2&FolderCTID=0x012000C815322C717A7E4B8164EA374FA254EC002682B939F9BED347BD49E43D77D3C691&View=%7B94C838B2%2DE166%2D4122%2DB8B4%2D7BEB9E1BC12B%7D#InplviewHash94c838b2-e166-4122-b8b4-7beb9e1bc12b=RootFolder%3D%252FOGAC%252DHQ%252Ficpi%252FShared%2520Documents%252FClusters%252FPrevention%252FWorking%2520Folder%252FDREAMS%252FFY19%252C%2520Q2

**Comment by HoustonJamie** [comment]
Hi JP and Jamie,

Thank you for your very helpful feedback. I’ve made the changes.

All the best,
Kimi

From: Houston, James C. (CDC/DDPHSIS/CGH/DGHT) [mailto:vie3@cdc.gov]
Sent: Thursday, May 23, 2019 4:14 PM
To: ICPI/Coordination <reply@reply.github.com>; ICPI/Coordination <Coordination@noreply.github.com>
Cc: Assign <assign@noreply.github.com>; Sato, Kimi <ksato@peacecorps.gov>; Erin Schelar <eschelar@usaid.gov>
Subject: RE: [ICPI/Coordination] Product Submission: New AGYW_PREV Visuals in DREAMS Dashboard (#63)

Kimi

Additionally, I noticed in the updated version you sent, for South Africa and Mozambique the formatting for the color in the bar charts is inconsistent with the other OUs.  I think its something about how they only have 1 or 2 values reported instead of all three options.

Otherwise looks great.  Cleared with minor comments.

Jamie

https://www.pepfar.net/OGAC-HQ/icpi/Shared%20Documents/Forms/AllItems.aspx?RootFolder=%2FOGAC%2DHQ%2Ficpi%2FShared%20Documents%2FClusters%2FPrevention%2FWorking%20Folder%2FDREAMS%2FFY19%2C%20Q2&FolderCTID=0x012000C815322C717A7E4B8164EA374FA254EC002682B939F9BED347BD49E43D77D3C691&View=%7B94C838B2%2DE166%2D4122%2DB8B4%2D7BEB9E1BC12B%7D#InplviewHash94c838b2-e166-4122-b8b4-7beb9e1bc12b=RootFolder%3D%252FOGAC%252DHQ%252Ficpi%252FShared%2520Documents%252FClusters%252FPrevention%252FWorking%2520Folder%252FDREAMS%252FFY19%252C%2520Q2

**Comment by jb3436** [comment]
Approved. Closing out. These will also be incorporated into the new dreams dossier https://github.com/ICPI/DIV/issues/134
