### ISSUE TITLE
Product Submission: Viral Load Tool (Diagnosis)

### ISSUE THREAD

**Issue by hessionra** [ICPI/Coordination#7]
Submission 1 - FY18Q2
--
Diagnosis Cluster submitted the Viral Load tool for ICPI Leads' review on Wednesday, April 4. Will be brought to Leads on Monday, April 9 (will assign Leads for review).

VL Tool is on SharePoint [Here](https://www.pepfar.net/OGAC-HQ/icpi/Shared%20Documents/Forms/AllItems.aspx?RootFolder=%2FOGAC%2DHQ%2Ficpi%2FShared%20Documents%2FClusters%2FHIV%2DTB%20Diagnosis%2FWorking%20Folder&FolderCTID=0x012000C815322C717A7E4B8164EA374FA254EC002682B939F9BED347BD49E43D77D3C691&View=%7B94C838B2%2DE166%2D4122%2DB8B4%2D7BEB9E1BC12B%7D&InitialTabId=Ribbon%2ERead&VisibilityContext=WSSTabPersistence)

Labeled [Zambia VLSD 2018 4 4](https://www.pepfar.net/OGAC-HQ/icpi/Shared%20Documents/Clusters/HIV-TB%20Diagnosis/Working%20Folder/Zambia_VLSD_%202018_4_4.xlsb)

**Comment by Yabayabadoo** [comment]
R-Script posted in Repo here : https://github.com/ICPI/Coordination/tree/Yabayabadoo-patch-1

**Comment by jb3436** [comment]
Review completed and Email sent to cluster leads 4/20

**Comment by hessionra** [comment]
@Yabayabadoo responded to reviewers (@jaliasd @jb3436 @kkale25 ) with clarifying questions; team hopes to resubmit tool this Friday 4/27.

**Comment by jb3436** [comment]
Setting up a meeting next week with the cluster leads and tool developers to review feedback.

**Comment by hessionra** [comment]
Resubmitted for Leads' review for FY18Q4 initial by @anu87 on behalf of Diagnosis Cluster 11/7. @jaliasd and @kkale25 assigned for Leads' review.

Josh and Kashmira responded with feedback 11/13, which can be found on [SharePoint](https://www.pepfar.net/OGAC-HQ/icpi/Shared%20Documents/Forms/AllItems.aspx?RootFolder=%2FOGAC%2DHQ%2Ficpi%2FShared%20Documents%2FManagement%20and%20Processes%2FICPI%20Leads%20Meetings%2FLeads%20Review%2FViral%20Load%20Review&FolderCTID=0x012000C815322C717A7E4B8164EA374FA254EC002682B939F9BED347BD49E43D77D3C691&View=%7B94C838B2%2DE166%2D4122%2DB8B4%2D7BEB9E1BC12B%7D&InitialTabId=Ribbon%2ERead&VisibilityContext=WSSTabPersistence).

**Comment by jb3436** [comment]
Submission 3 - FY19Q1

Anu submitted VL tool for leads review 2/15
Assigned 2/21
Review by 2/22 
Response sent ___

**Comment by jb3436** [comment]
Feedback on Submission 3
--

**Overall Feedback**
•	Great work, it incorporates a nice picture of VL
•	Functionality is good
•	Look forward to seeing how the Q1 data respond
•	Minor notes, the acronyms viral load coverage (VLC) and viral load suppression (VLS) are not spelled out.  I suggest adding this to the start here tab and to the purple title bar (there is space) and it will break up the many acronyms. 
### 
**Tab by Tab Review**
**Start Here Tab**
•	Please add ICPI@state.gov to the contact page (made this change)
•	Please update this tab with all of the calculations, acronyms, etc as well as some of the logic so new users will understand the tool more easily. 
 
**Viral Load Performance Tab**
There is a lot of great information on this chart, but it is losing its message with all of the callout items. 

**•	Missing**
    o	What are the plans to standardize feedback times so that requirements can be gathered in enough time to make updates to the tool
o	Not all of the analyses that the VL COOP asked for have been incorporated, but some have.  What are the plans to incorporate items like below:

**•	Color** 
o	Suggest being consistent in color choice for suppressed, unsuppressed, gap, etc. 
o	In the below snapshot sometimes it is green, sometimes blue. Also suggest using a neutral color if a pattern is used. Grey would be easier to absorb visually than the orange. 
o	Some of these formatting changes have been made directly

**ADDED - Site Level VL Performance** 
•	May want to rename it something else - scatterplot or site level scatterplot or leave as is. Up to you
 
**Potential Barriers Tab**
•	Hard to see the chart with the data labels - consider a table below and only including the % as data labels in the chart

**Style review**
o	Will do a style review and make updates directly to the template. 
o	Uploaded to SP here 
https://www.pepfar.net/OGAC-HQ/icpi/Shared%20Documents/Forms/AllItems.aspx?RootFolder=%2FOGAC%2DHQ%2Ficpi%2FShared%20Documents%2FClusters%2FHIV%2DTB%20Diagnosis%2FWorking%20Folder&FolderCTID=0x012000C815322C717A7E4B8164EA374FA254EC002682B939F9BED347BD49E43D77D3C691&View=%7B94C838B2%2DE166%2D4122%2DB8B4%2D7BEB9E1BC12B%7D&InitialTabId=Ribbon%2ERead&VisibilityContext=WSSTabPersistence
•	Changes made (not completely comprehensive)
o	Updates axis on this chart to make both of them set to 100%, one was set to 90%
VLC & VLS by Age Fine and Sex, 
FY18APR - FY19Q1
o	Changed colors to consistently represent VLC and VLS across charts and tabs
o	Reduced number of colors - hard for user to follow too many
o	Updated the slicer order and layout so that geography and partner items are all in a row instead of mixed
o	Inserted titles into each tab
o	Reformatted all tables to be same color scheme and layout
o	Broke the below table into two and placed them under the corresponding charts in the tool

**Outstanding Items (not fully completed as part of updates made)**
o	I put a placeholder in the VL trends tab, but didn’t make sure that the right pivot table was selected
o	Please make sure that the term for VL Suppression and VL coverage is consistent. It says "VLC" in one place and "proxy VL Coverage". Suggest sticking with "VL Coverage" label. 
o	Same for VL Suppression - in one tab it says "VLS" and in another it says "suppressed", please use the label "VL Suppression"
o	Also, may want to be consistent in referring to a rate vs. absolute values. In VL trends, VLS includes both the absolute value and the suppression "rate". Wherever it is a %, please consistently refer to it as a rate or percentage to make it easier for the end user
o	Please clarify the elements in the tool - where there are absolute values and rates
o	Consistently refer to "undocumented test indication" and "patients without VL documentation" 
o	Please add calculations to start here tab for all items in the workbook, example
•	Patients without VL documentation 
•	VL suppression 
•	VL Suppression rate
•	Testing gap
o	I removed the labels from the daunt chart - it is too cumbersome to have the labels. I tried to add a data table below instead.  It didn't work. Could you add it? Or insert a simple table below that pulls from the pivot tables if the data table isn't good. 
o	Probably a good idea to set up tables below the charts to streamline the visuals and separate out the data from the visuals. Using both is a lot. 
o	Can you replicate this for these visuals, which will make the visuals stand out and still convey the data
o	You can keep the data labels for the % only.  (did most of this, use your judgement on how to proceed)

**Substance and Overall Structure**
•	Comments interspersed through tab/tab comments – please see above
•	This is an improvement on the previous version, where there  is more parsimony in the number of visuals and the story being told.  WE expect this to continue to evolve now that the tool is quarterly.
•	The color scheme/look and feel needs to be harmonized a bit more so the user doesn’t have to switch perspectives as colors shift for the same metric. Some of this was directly modified in the template. Please be conscious of this. VLS should be the same color in every chart. 

**Statistics and Data Quality**
•	Once this is populated with real data, kindly submit your QC documentation 
•	Need some additional description of some of the elements included
•	Need to describe ALL of the calculations made in the start here tab and define clearly how they should be interpreted

**Decision (Approved/Revision Recommended/Not Approved)**
•	Revision and resubmission to ICPI@state.gov recommended for further review
•	Once you have determined how long the process to integrate the feedback will take, kindly provide an updated target submission time so we can be sure to be ready for a fast turnaround review
Additional Clearance Needed from Other Stakeholders?
•	Please make sure you POCs in the VL COOP have provided feedback

**Comment by jb3436** [comment]
Submission 3 Revision Submission and Approval
--
Revision Submitted Wed 3/6
Approval Sent Friday 3/8  


Email Submitted (RE: VL Tool FY19Q1)
--
Hi All,

Please find the new version of VL tool here: https://www.pepfar.net/OGAC-HQ/icpi/Shared%20Documents/Clusters/HIV-TB%20Diagnosis/Working%20Folder/VL_Tool_Global_FY19Q1_030619_V5.xlsb 

I have added some of my responses have to the feedback document.

Changes made:
Populated the tool with FY19Q1 data. Tool is not QC’d. Cameroon had no data (for VL incators) in Site-IM MSD, so that data is missing in the tool
1.	Start here tab:
a.	Added formulae for calculated indicators
2.	VL Trends
a.	Incorporated all the color scheme changes
3.	VL Performance
a.	Incorporated layout changes
b.	Added data tables under the graph
c.	Incorporated all the color scheme changes
d.	Moved site-level table to new tab
4.	Site-level VL Performance
a.	Added a note on the bubble graph
b.	Incorporated layout changes
5.	Potential Barriers:
a.	Incorporated layout changes
b.	Added data tables under Retention graphs

Email Response (RE: APPROVED: VL Tool FY19Q1) 
--

Dear Anu, 
CC’d Diagnosis Cluster leads and ICPI Leads 

All changes suggested to the VL tool have been incorporated. I would like to highlight the great work in describing all of the calculations and improving the consistency in the metrics throughout the tool. 

DECISION: The tool is approved for FY19 Q1.  

Leads feel free to share any additional comments or concerns, which can be included in the FY19Q1 clean revision. 

Links
[SharePoint: VSLD](https://www.pepfar.net/OGAC-HQ/icpi/Shared Documents/Forms/AllItems.aspx?RootFolder=%2FOGAC%2DHQ%2Ficpi%2FShared%20Documents%2FClusters%2FHIV%2DTB%20Diagnosis%2FWorking%20Folder&FolderCTID=0x012000C815322C717A7E4B8164EA374FA254EC002682B939F9BED347BD49E43D77D3C691&View=%7B94C838B2%2DE166%2D4122%2DB8B4%2D7BEB9E1BC12B%7D&InitialTabId=Ribbon%2ERead&VisibilityContext=WSSTabPersistence#InplviewHash94c838b2-e166-4122-b8b4-7beb9e1bc12b=FolderCTID%3D0x012000C815322C717A7E4B8164EA374FA254EC002682B939F9BED347BD49E43D77D3C691-InitialTabId%3DRibbon%252ERead-VisibilityContext%3DWSSTabPersistence-SortField%3DModified-SortDir%3DDesc-RootFolder%3D)

**Comment by jb3436** [comment]
Moved into dossiers August 2019
